# Generated by Django 5.0.6 on 2024-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('sl_number', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/candidate_image')),
                ('votes', models.IntegerField(default=0)),
                ('candidate_party', models.CharField(max_length=100)),
                ('candidate_party_logo', models.ImageField(upload_to='images/candidate_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.SmallIntegerField()),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('card_number', models.CharField(default=True, max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Voters',
            },
        ),
    ]
