# Generated by Django 5.0.6 on 2024-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='candidate_party_logo',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='image',
        ),
        migrations.AlterField(
            model_name='voters',
            name='card_number',
            field=models.CharField(default='RAR9394963', max_length=10, unique=True),
        ),
    ]
