# Generated by Django 5.0.6 on 2024-06-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0002_remove_candidates_candidate_party_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='card_number',
            field=models.CharField(default='MSY4713105', max_length=10, unique=True),
        ),
    ]
