# Generated by Django 5.0.6 on 2024-06-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0004_alter_candidates_options_voters_already_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='voted_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pole.candidates'),
        ),
        migrations.AlterField(
            model_name='voters',
            name='card_number',
            field=models.CharField(default='ONX1357210', max_length=10, unique=True),
        ),
    ]
